require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/stats", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Stats. As you add validations to Stats, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Stats.create! valid_attributes
      get stats_index_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      stats = Stats.create! valid_attributes
      get stat_url(stats)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_stat_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      stats = Stats.create! valid_attributes
      get edit_stat_url(stats)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Stats" do
        expect {
          post stats_index_url, params: { stat: valid_attributes }
        }.to change(Stats, :count).by(1)
      end

      it "redirects to the created stat" do
        post stats_index_url, params: { stat: valid_attributes }
        expect(response).to redirect_to(stat_url(Stats.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Stats" do
        expect {
          post stats_index_url, params: { stat: invalid_attributes }
        }.to change(Stats, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post stats_index_url, params: { stat: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested stat" do
        stats = Stats.create! valid_attributes
        patch stat_url(stats), params: { stat: new_attributes }
        stats.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the stat" do
        stats = Stats.create! valid_attributes
        patch stat_url(stats), params: { stat: new_attributes }
        stats.reload
        expect(response).to redirect_to(stat_url(stats))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        stats = Stats.create! valid_attributes
        patch stat_url(stats), params: { stat: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested stat" do
      stats = Stats.create! valid_attributes
      expect {
        delete stat_url(stats)
      }.to change(Stats, :count).by(-1)
    end

    it "redirects to the stats list" do
      stats = Stats.create! valid_attributes
      delete stat_url(stats)
      expect(response).to redirect_to(stats_index_url)
    end
  end
end
